# generated by datamodel-codegen:
#   filename:  p.json
#   timestamp: 2024-05-08T12:08:47+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class Search:
    label: str
    href: str


@dataclass
class Data:
    searches: List[Search]


@dataclass
class PopularSearchesResponse:
    data: Data
